In [2]:
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
import numpy as np

C:\Users\david\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
C:\Users\david\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)

In [5]:
path="C://Users//david\Desktop//VU amsterdam//Data mining"
train = pd.read_csv(path+"/Preprocessed_train.csv")
train.head()

,Unnamed: 0,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,0,43,2013-01-09 16:45:45,5,219,NaN,NaN,219,7011,2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,43,2013-01-09 16:45:45,5,219,NaN,NaN,219,8797,2,...,NaN,NaN,NaN,NaN,1.0,0.0,34.0,0,NaN,0
2,2,43,2013-01-09 16:45:45,5,219,NaN,NaN,219,14530,3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,3,43,2013-01-09 16:45:45,5,219,NaN,NaN,219,15770,2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
4,4,43,2013-01-09 16:45:45,5,219,NaN,NaN,219,20295,3,...,NaN,NaN,NaN,NaN,1.0,0.0,42.0,0,NaN,0

### Modify the dataset for RandomForest regression and other standard ML algorithm

In [ ]:
#Adding Score columns: 5 for booked, 1 clicked and 0 the rest
train['c'] = train.apply(lambda x: max(len(x['a']), len(x['b'])), axis=1)